package com.binance.api.client.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Ordenar os valores da razão de rejeição.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public enum OrderRejectReason {
  NONE, // NENHUM
  UNKNOWN_INSTRUMENT, // INSTRUMENTO DESCONHECIDO
  MARKET_CLOSED, // MERCADO FECHADO
  PRICE_QTY_EXCEED_HARD_LIMITS, // A QUANTIDADE DE PREÇOS EXCEDE LIMITES DUROS
  UNKNOWN_ORDER, // ORDEM DESCONHECIDA
  DUPLICATE_ORDER, // PEDIDO DUPLICADO
  UNKNOWN_ACCOUNT, // CONTA DESCONHECIDA
  INSUFFICIENT_BALANCE, // SALDO INSUFICIENTE
  ACCOUNT_INACTIVE, // CONTA INATIVA
  ACCOUNT_CANNOT_SETTLE, // CONTA NÃO PODE RESOLVER
  ORDER_WOULD_TRIGGER_IMMEDIATELY // ORDEM LIBERARIA IMEDIATAMENTE
}